# Generated by Django 4.2.8 on 2024-06-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='filename',
        ),
    ]
